### ISSUE TITLE
VideoWidgetDemo won't play anything other than the sample video.

### ISSUE THREAD

**Issue by andr3wmac** [googlesamples/cardboard-ios#4]
I've been unable to get the VideoWidgetDemo sample to play another video file. It shows nothing but white where the video should be followed by the app crashing after a few seconds with "Message from debugger: Terminated due to memory issue."

I've tried videos we encoded as well as videos from this page:
http://photocreations.ca/3D/

And I can't find a single video outside of the provided congo.mp4 that will play on iPad or iOS using the sample. I've tried the same videos in the cardboard-android sdk with no issues. Also, we have a native player application that uses AVFoundation to decode these videos and play them back on the same devices so I don't suspect the device itself is to blame for this.

**Comment by nathanmartz** [comment]
Did you grab the 0.7.1 cocopod? We fixed a related issue on Friday.

**Comment by congsun** [comment]
@nathanmartz It still crash on mine, but not as before, it crashes immediately.
```2016-04-04 14:55:54.370 Google360Video[1897:18511] Invalid atom size.
2016-04-04 14:55:54.370 Google360Video[1897:18511] Invalid atom size.
2016-04-04 14:55:54.371 Google360Video[1897:18511] Invalid atom size.
2016-04-04 14:55:54.371 Google360Video[1897:18511] Invalid atom size.
2016-04-04 14:55:54.381 Google360Video[1897:18511] Invalid atom size.
2016-04-04 14:55:54.381 Google360Video[1897:18511] Invalid atom size.
2016-04-04 14:55:54.381 Google360Video[1897:18511] Invalid atom size.
2016-04-04 14:55:54.381 Google360Video[1897:18511] Invalid atom size.
2016-04-04 14:55:54.382 Google360Video[1897:18511] Invalid atom size.
2016-04-04 14:55:54.383 Google360Video[1897:18511] Invalid atom size.
2016-04-04 14:55:54.384 Google360Video[1897:18511] Invalid atom size.
2016-04-04 14:55:54.384 Google360Video[1897:18511] Invalid atom size.
2016-04-04 14:55:54.385 Google360Video[1897:18511] Invalid atom size.
2016-04-04 14:55:54.385 Google360Video[1897:18511] Invalid atom size.
2016-04-04 14:55:54.386 Google360Video[1897:18511] Invalid atom size.
2016-04-04 14:55:54.386 Google360Video[1897:18511] Invalid atom size.
2016-04-04 14:55:54.386 Google360Video[1897:18511] Invalid atom size.
2016-04-04 14:55:54.388 Google360Video[1897:18511] Invalid atom size.
2016-04-04 14:55:54.400 Google360Video[1897:18511] *** Assertion failure in -[GCSVideoView onMetadataParsed:], googlemac/iPhone/CardboardSDK/Source/GCSVideoView.mm:227
2016-04-04 14:55:54.407 Google360Video[1897:18511] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error at CVOpenGLESTextureCacheCreate -6661'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010ab65d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010a5d9deb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ab65bea +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x000000010a223d5a -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	4   Google360Video                      0x00000001084662d2 -[GCSVideoView onMetadataParsed:] + 838
	5   Google360Video                      0x0000000108465c3e -[GCSVideoView connection:didReceiveData:] + 421
	6   CFNetwork                           0x000000010e534a36 __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 69
	7   CFNetwork                           0x000000010e5349da -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 199
	8   CFNetwork                           0x000000010e534b2f -[NSURLConnectionInternal _withActiveConnectionAndDelegate:] + 48
	9   CFNetwork                           0x000000010e509166 _ZL30_NSURLConnectionDidReceiveDataP16_CFURLConnectionPK8__CFDatalPKv + 79
	10  CFNetwork                           0x000000010e399655 ___ZN27URLConnectionClient_Classic29_delegate_didReceiveDataArrayEv_block_invoke + 293
	11  CFNetwork                           0x000000010e48fd75 ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2 + 100
	12  libdispatch.dylib                   0x000000010c8613eb _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x000000010c84348b _dispatch_block_invoke + 716
	14  CFNetwork                           0x000000010e38860a _ZN19RunloopBlockContext13_invoke_blockEPKvPv + 24
	15  CoreFoundation                      0x000000010aa5e894 CFArrayApplyFunction + 68
	16  CFNetwork                           0x000000010e388503 _ZN19RunloopBlockContext7performEv + 137
	17  CFNetwork                           0x000000010e3883bc _ZN17MultiplexerSource7performEv + 282
	18  CFNetwork                           0x000000010e3881de _ZN17MultiplexerSource8_performEPv + 72
	19  CoreFoundation                      0x000000010aa8b301 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	20  CoreFoundation                      0x000000010aa8122c __CFRunLoopDoSources0 + 556
	21  CoreFoundation                      0x000000010aa806e3 __CFRunLoopRun + 867
	22  CoreFoundation                      0x000000010aa800f8 CFRunLoopRunSpecific + 488
	23  GraphicsServices                    0x000000010ddaaad2 GSEventRunModal + 161
	24  UIKit                               0x000000010b1c1f09 UIApplicationMain + 171
	25  Google360Video                      0x000000010844f06f main + 111
	26  libdyld.dylib                       0x000000010c89592d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by andr3wmac** [comment]
@nathanmartz : I did not, just updated it and the issue appears to be resolved :+1: 

@congsun  : I'm closing this issue since my specific problem is resolved, please open another issue for yours, I'm not entirely convinced they're related despite similarities, otherwise I'd leave this issue open.
